### ISSUE TITLE
decrypt + PipedOutputStream

### ISSUE THREAD

**Issue by bilus** [thi-ng/crypto#2]
I cannot figure out how to make `decrypt` and `encrypt-stream` work with pipes.

``` clojure
(with-open [in (io/input-stream "backup.enc")
              out (PipedOutputStream.)
              out2 (PipedInputStream. out)]
    (crypto/encrypt-stream in out (crypto/public-key "alice.pub.asc"))
    (loop []
      (let [x (.read out2)]
        (println x)
        (when (not= x -1)
          (recur)))))
```

It just hangs. Any clues?

**Comment by postspectacular** [comment]
Hi @bilus, thanks for your interest, but AFAIK it's not recommended to use PipedOutputStreams in a single threaded mode since it can (and in this case probably does) deadlock:

http://docs.oracle.com/javase/7/docs/api/java/io/PipedOutputStream.html

"Typically, data is written to a PipedOutputStream object by one thread and data is read from the connected PipedInputStream by some other thread. Attempting to use both objects from a single thread is not recommended as it may deadlock the thread."

I don't have much experience with this class either so can't really help in this case (right now), but will do some experiments myself asap...

**Comment by bilus** [comment]
UPDATE: Please disregard it, my bad. Just noticed that bytes are copied into the output stream and, obviously, it hangs since it's done on the same thread. 

Using futures solves the "problem":

``` clojure
(with-open [in-stream (io/input-stream "README.md")
            out-pipe (PipedOutputStream.)
  (let [encryption-task (future (with-open [out-stream (io/output-stream out-pipe)]
                                  (crypto/encrypt-stream in-stream out-stream (crypto/public-key "alice.pub.asc"))))
        encrypted-stream (PipedInputStream. out-pipe)]
    ;; read from the encrypted stream, pass it on etc.
    ;; Example:
    (loop []
      (let [x (.read encrypted-stream)]
        (println x)
        (when (not= x -1)
          (recur))))
    ;; Wait for the future to complete
    @encryption-task))
```

**Comment by postspectacular** [comment]
You should wrap the code which is reading from the pipe sink in a `future`... this should work!

**Comment by bilus** [comment]
Synchronicity lol. :) 

UPDATE: Just noticed I did it the other way round. Either way would work though. Thanks!
